const Images = {
  action: require('../assets/action.jpg'),
  addFriend: require('../assets/add-friend.png'),
  apple: require('../assets/apple.png'),
  arrow: require('../assets/arrow.png'),
  banner: require('../assets/banner.png'),
  bookmark: require('../assets/bookmark.png'),
  comedy: require('../assets/comedy.jpg'),
  crime: require('../assets/crime.jpg'),
  dollar: require('../assets/dollar.png'),
  email: require('../assets/email.png'),
  explore: require('../assets/explore.png'),
  google: require('../assets/google.png'),
  grid: require('../assets/grid.png'),
  help: require('../assets/help.png'),
  home: require('../assets/home.png'),
  insurance: require('../assets/insurance.png'),
  language: require('../assets/language.png'),
  list: require('../assets/list.png'),
  logo: require('../assets/logo.png'),
  logout: require('../assets/logout.png'),
  movieIcon: require('../assets/movie_icon.png'),
  movie1: require('../assets/movie1.jpg'),
  notification: require('../assets/notification.png'),
  password: require('../assets/password.png'),
  pen: require('../assets/pen.png'),
  playButton: require('../assets/play_button.png'),
  profile: require('../assets/profile.png'),
  review: require('../assets/review.png'),
  role: require('../assets/role.png'),
  romantic: require('../assets/romantic.jpeg'),
  sciFi: require('../assets/sci_fi.jpg'),
  search: require('../assets/search.png'),
  star: require('../assets/star.png'),
  termsCond: require('../assets/terms-and-conditions.png'),
  thriller: require('../assets/thriller.jpg'),
  trash: require('../assets/trash-bin.png'),
  user: require('../assets/user.png'),
  name: require('../assets/signature.png'),
  phone: require('../assets/telephone.png'),
  war: require('../assets/war.jpg'),
  cancel: require('../assets/close.png'),
  photo: require('../assets/gallery.png'),
};

export default Images;